baseURL = "https://malinoien.github.io/"
languageCode = "en-us"
title = "News"

theme = "heather-hugo"

[permalinks]
  post = "/:slug/"

[outputs]
  page = ["json", "HTML"]
  home = ["json", "HTML"]
  section = ["json", "HTML"]
